// Blog — longer-form, dated articles for the SEO + email funnel. Same shape as
// guides but with a date/author and a lead paragraph.
export interface BlogPost {
  slug: string
  title: string
  description: string
  date: string // ISO
  author: string
  readMins: number
  lead: string
  sections: Array<{ h: string; p: string }>
}

export const POSTS: BlogPost[] = [
  {
    slug: 'lahso-land-and-hold-short',
    title: 'LAHSO: land and hold short, and how to read it back',
    description: 'What a land-and-hold-short (LAHSO) clearance is, when you can accept or decline it, and exactly how to read it back.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 5,
    lead: 'LAHSO is one of the few clearances you are allowed to turn down, and one where reading it back correctly genuinely matters. Here is how it works.',
    sections: [
      { h: 'What LAHSO is', p: 'Land And Hold Short Operations: the tower clears you to land but you must stop before an intersecting runway or a marked point on the runway, to stay clear of crossing traffic on another runway.' },
      { h: 'You can decline it', p: 'If you are not comfortable with the available landing distance, or anything else, you may say “unable LAHSO” and the tower will sequence you another way. Student pilots are often advised to decline as a matter of course.' },
      { h: 'Check the available distance', p: 'The tower gives you the available landing distance — “hold short of runway three zero, four thousand five hundred feet available.” Make sure that is comfortably enough for your airplane before you accept.' },
      { h: 'The readback', p: 'Read back the hold-short point: “Cleared to land runway two six, hold short of runway three zero, Cessna One Two Three Four Five.” The hold-short is the part you must say.' },
      { h: 'If you accept, you must comply', p: 'Once you accept LAHSO you are committed to stopping short. Plan the approach and touchdown so the hold-short point is comfortable, not a scramble at the end.' },
      { h: 'When in doubt, decline', p: 'There is no penalty for “unable.” A normal landing on the full runway, or a go-around, is always safer than scraping to a stop to make a hold-short you were not sure about.' },
      { h: 'Drill it', p: 'The hold-short read-back is the most-failed call on a checkride and the most drillable. Practice LAHSO and hold-short read-backs on Clearspar — free, no mic.' },
    ],
  },
  {
    slug: 'how-to-give-a-pirep',
    title: 'How to give a PIREP (pilot report)',
    description: 'What a PIREP is, when to give one, and the format — so you can report what you are actually seeing to Flight Service or ATC.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 5,
    lead: 'A PIREP is how the weather you are flying through reaches the next pilot. Giving one is simple, genuinely useful, and something controllers and Flight Service actively want.',
    sections: [
      { h: 'What a PIREP is', p: 'A pilot report of actual conditions aloft — cloud tops and bases, turbulence, icing, in-flight visibility, wind. Forecasts are predictions; a PIREP is ground truth from someone who is up there now.' },
      { h: 'When to give one', p: 'Anytime conditions differ from the forecast, or when you hit turbulence, icing, or a cloud layer worth reporting. Unexpectedly smooth air and clear tops are worth reporting too — good news helps the next pilot plan.' },
      { h: 'Who to give it to', p: 'Flight Service on a published frequency or 122.2, or the ATC controller you are already talking to. Open with “[facility], Cessna One Two Three Four Five, PIREP” so they can get ready to copy.' },
      { h: 'The format', p: 'Location, time, altitude, aircraft type, then the conditions: “over the Hilo VOR, one five past the hour, six thousand five hundred, Cessna 172, tops of the layer at six thousand, light chop.” The order is standard, but they will take whatever you can give.' },
      { h: 'Use the standard intensities', p: 'For turbulence: light, moderate, severe, extreme. For icing: trace, light, moderate, severe. Those words mean specific things to the next pilot, so use them rather than your own description.' },
      { h: 'Why it matters', p: 'The next pilot and the forecaster both use your report. It is one of the few ways general aviation gives back to the system it relies on.' },
      { h: 'Drill the call', p: 'Practice the structured report so it comes out in order under a little workload. Free on Clearspar, no mic required.' },
    ],
  },
  {
    slug: 'special-vfr-how-to-request',
    title: 'Special VFR: what it is and how to request it',
    description: 'When special VFR lets you operate below basic VFR minimums, how to request it, and the limits and traps to know.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 5,
    lead: 'Special VFR is a clearance that lets you operate in a control zone with less than basic VFR weather. It is a useful tool with real limits and a few genuine traps.',
    sections: [
      { h: 'What special VFR is', p: 'A clearance to fly in the surface area of controlled airspace (Class B, C, D, or a Class E surface area) with less than basic VFR minimums: at least one statute mile visibility and clear of clouds, instead of the usual three miles and cloud-clearance distances.' },
      { h: 'You have to ask for it', p: 'ATC will not offer special VFR — you request it: “Tower, Cessna One Two Three Four Five, request special VFR clearance to depart to the south.” They coordinate the airspace and clear you.' },
      { h: 'The minimums', p: 'One statute mile visibility and remain clear of clouds. At night, you generally need an instrument rating and an IFR-capable airplane to be granted special VFR at all.' },
      { h: 'The readback', p: 'Read back the clearance: “Cleared out of the Class Delta to the south, maintain special VFR conditions, Cessna One Two Three Four Five.” You are responsible for staying in special-VFR conditions.' },
      { h: 'The trap', p: 'It is legal, not always smart. One mile and clear of clouds near terrain or obstacles is genuinely marginal, and special VFR has hurt pilots who treated the clearance as permission to push into weather they should have waited out.' },
      { h: 'Where you cannot get it', p: 'Some busy Class B airports prohibit special VFR for fixed-wing aircraft; it is noted on the chart. Check before you count on it.' },
      { h: 'Drill the request', p: 'Practice the special-VFR request and read-back on Clearspar so the words are there if you ever genuinely need them. Free, no mic.' },
    ],
  },
  {
    slug: 'transponder-squawk-codes',
    title: 'Squawk codes: 1200, ident, and the emergency codes',
    description: 'What to set your transponder to — 1200 for VFR, assigned codes, ident, and the 7500 / 7600 / 7700 emergency codes.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 5,
    lead: 'The transponder is how ATC sees you on radar, and “squawk” is the word for setting it. A handful of codes are worth knowing cold — especially the emergency ones.',
    sections: [
      { h: 'What “squawk” means', p: 'When ATC says “squawk four two seven one,” they want that code set in your transponder. It tags your radar return so they can pick you out from everyone else on the scope.' },
      { h: '1200 — the VFR code', p: 'If you are flying VFR and not receiving flight following or any other service, you squawk 1200. It simply marks you as a VFR aircraft.' },
      { h: '“Ident”', p: 'When ATC says “Cessna One Two Three Four Five, ident,” you press the IDENT button. It makes your return blossom on their scope so they can confirm which target is you. You do not read it back — you just push the button.' },
      { h: 'Assigned codes', p: 'When you pick up flight following or an IFR clearance, ATC assigns a discrete code. Set it and read it back: “Squawk four two seven one, Cessna One Two Three Four Five.”' },
      { h: 'The emergency codes', p: '7500 is hijack, 7600 is lost communications (radio failure), and 7700 is a general emergency. A common memory aid: 7500 taken alive, 7600 cannot talk no more, 7700 going to heaven. When something is wrong and you are not sure, 7700 gets everyone’s attention.' },
      { h: 'Do not trip the alarms', p: 'Try not to spin the knob through 7500, 7600, or 7700 on your way to another code, or you can set off alerts. Many modern transponders guard against it, but change codes deliberately.' },
      { h: 'Drill the readbacks', p: 'Practice setting and reading back assigned squawk codes on Clearspar until it is automatic. Free, no mic.' },
    ],
  },
  {
    slug: 'position-reports-say-position',
    title: 'Position reports: what to say when ATC asks “say position”',
    description: 'How to give a position report — over a fix, on flight following, or at a non-towered field — so others know where you are.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 5,
    lead: '“Say position” can catch a new pilot flat-footed. A position report is just a quick, structured way of saying where you are — once you know the shape of it, it is easy.',
    sections: [
      { h: 'The basic shape', p: 'Who you are, where you are, your altitude, and what you are doing: “Cessna One Two Three Four Five, ten miles south of the field, four thousand five hundred, inbound to land.” That covers almost every case.' },
      { h: 'Reporting over a fix', p: 'On a route, report relative to a VOR or named fix: “over the Hilo VOR, four thousand five hundred.” A radial and distance works too: “one five DME on the two seven zero radial.”' },
      { h: 'On flight following', p: 'If a controller loses your track or just asks, “say position” wants your location relative to a landmark or fix plus your altitude. Keep it short — they are re-finding you, not reading a story.' },
      { h: 'At a non-towered field', p: 'Your self-announce calls are position reports to other traffic: “[field] traffic, Cessna One Two Three Four Five, left downwind runway two six, [field].” Position, intention, field name as the bookends.' },
      { h: 'Use landmarks people know', p: 'A town, a lake, a VOR, a highway — something on the chart, not “near my house.” The whole point is that the other person can find you from what you said.' },
      { h: 'Keep it brief', p: 'Position, altitude, intention. You are painting a quick picture so the next person knows where to look, not narrating the flight.' },
      { h: 'Drill it', p: 'Practice tight position reports on Clearspar until the shape is automatic. Free, works offline, no mic.' },
    ],
  },
  {
    slug: 'ifr-approach-phraseology',
    title: 'IFR approach phraseology: the calls from clearance to the missed',
    description: 'The radio calls on an instrument approach — cleared for the approach, reporting established, the handoff, and the missed — and how to read them back.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 6,
    lead: 'The instrument approach has its own short, specific set of calls. Knowing them cold removes one more task from the busiest few minutes in instrument flying.',
    sections: [
      { h: '“Cleared for the approach”', p: 'ATC clears you for a specific approach: “Cessna One Two Three Four Five, cleared for the ILS runway two six approach.” Read it back with the approach name: “Cleared for the ILS runway two six, Cessna One Two Three Four Five.”' },
      { h: 'Vectors to final', p: 'On radar vectors, ATC turns you onto the final approach course and clears you, usually with an altitude: “maintain two thousand until established, cleared for the approach.” Read back the altitude and the clearance together.' },
      { h: '“Report established”', p: 'When asked, report when you intercept the final approach course: “established on the localizer, Cessna One Two Three Four Five.” It tells ATC you are on the approach and they can stop watching your turn.' },
      { h: 'The handoff to tower or advisory', p: 'Approach hands you to the tower, or to the advisory frequency at a non-towered field: “contact tower one one niner point three” or “change to advisory frequency approved.” Read it back and switch.' },
      { h: 'The missed approach', p: 'If you go missed, fly the published missed approach and tell ATC: “Cessna One Two Three Four Five, missed approach,” then your intentions. They will give you a clearance to try again or to divert.' },
      { h: 'Cancelling IFR', p: 'At a non-towered field in VFR conditions, you can cancel IFR with ATC or Flight Service once the airport is made: “cancel IFR, Cessna One Two Three Four Five.” It frees the approach for the next aircraft.' },
      { h: 'Drill the sequence', p: 'Practice the approach calls in order on Clearspar so the radio is the easy part of the approach, not another thing to juggle. Free, no mic.' },
    ],
  },
  {
    slug: 'how-to-copy-atis',
    title: 'How to copy the ATIS and report you have it',
    description: 'What the ATIS is, how to copy it without falling behind, and what “with information Charlie” tells the controller.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 5,
    lead: 'The ATIS is the first radio thing you do at a towered field, and it sets up every call after it. Copy it cleanly and you walk onto the frequency already ahead of the airplane.',
    sections: [
      { h: 'What the ATIS is', p: 'The ATIS is a recorded loop of the airport’s current weather, the active runway, and any notices, updated each hour or whenever conditions change. You listen to it before you call anyone.' },
      { h: 'The information letter', p: 'Each update is tagged with a letter — Alpha, Bravo, Charlie, and on through the alphabet. Quoting the letter on your first call tells the controller exactly which set of conditions you already have.' },
      { h: 'What to copy', p: 'At a minimum: the active runway, the altimeter, the wind, and the information letter. Many pilots jot just those four and that is enough to sound squared-away on the first call.' },
      { h: '“With information Charlie”', p: 'On your first call to ground or tower, you add “with information Charlie.” It tells the controller you already have the weather, so they do not have to read it to you.' },
      { h: 'If you do not have it', p: 'If you could not copy it, say “negative ATIS” or “request the altimeter.” Asking is always better than bluffing your way onto the field without the current numbers.' },
      { h: 'Listen for the change', p: 'The recording ends with “advise you have information Charlie.” When a new letter comes out, the runway or weather may have changed — recopy it, because the controller is now expecting the new letter.' },
      { h: 'Drill it', p: 'Copying the ATIS quickly is a habit you build by reps. Practice the calls that follow it — your first ground and tower calls — graded and free on Clearspar.' },
    ],
  },
  {
    slug: 'radio-failure-light-gun-signals',
    title: 'Radio failure: light gun signals and what to do (NORDO)',
    description: 'What to do when your radio quits near a towered airport — the tower’s light gun signals and how to acknowledge them.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 6,
    lead: 'A dead radio is not an emergency, but it is a moment you want rehearsed before it happens. The tower can still talk to you with a light gun, and you can still land safely.',
    sections: [
      { h: 'First, troubleshoot', p: 'Before you declare anything lost, check the volume, the squelch, the frequency, the headset plugs, and the audio panel. Most “radio failures” turn out to be a knob in the wrong place.' },
      { h: 'If it is truly dead', p: 'Squawk 7600, the lost-communications code, and fly toward the airport. You can still land at a towered field without a radio — the tower will direct you with a light gun.' },
      { h: 'The light gun signals', p: 'Steady green: cleared to land in the air, cleared for takeoff on the ground. Flashing green: return for landing in the air, cleared to taxi on the ground. Steady red: give way and keep circling in the air, stop on the ground. Flashing red: airport unsafe, do not land in the air; taxi clear of the runway on the ground. Flashing white (on the ground): return to your starting point on the airport. Alternating red and green: general warning, use extreme caution.' },
      { h: 'How to acknowledge', p: 'Let the tower know you saw the signal. By day, rock your wings. By night, flash your landing light or your navigation lights.' },
      { h: 'A way to remember it', p: 'Steady is a state, flashing is an instruction; green generally means come or go, red generally means stop or stay. You will not use this often, so the time to learn it cold is on the ground.' },
      { h: 'Rehearse the recovery', p: 'The calm in a real radio failure comes from having pictured it beforehand. Practice the normal towered calls until they are automatic, so a quiet radio is the only new variable. Free on Clearspar.' },
    ],
  },
  {
    slug: 'cleared-for-the-option',
    title: 'What “cleared for the option” means (and how to read it back)',
    description: 'The option clearance lets you choose your maneuver on landing — what it covers, why instructors love it, and how to read it back.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 5,
    lead: 'New students hear “cleared for the option” and freeze, because it is not one of the clearances they studied. It is actually one of the most useful calls in primary training.',
    sections: [
      { h: 'What “the option” is', p: 'It clears you to do any of several maneuvers on the approach: a touch-and-go, a stop-and-go, a low approach, a go-around, or a full-stop landing. You choose which one, in the air.' },
      { h: 'Why instructors request it', p: 'With the option, your CFI can have you fly a touch-and-go, then switch to a full stop, without asking the tower for a new clearance each time. It keeps the lesson flexible.' },
      { h: 'How to request it', p: '“Tower, Cessna One Two Three Four Five, request the option.” You usually ask for it when you check in inbound or as you turn downwind.' },
      { h: 'The readback', p: '“Cleared for the option, Cessna One Two Three Four Five.” That is the whole read-back — you do not have to tell the tower which maneuver you are going to pick.' },
      { h: 'The maneuvers it covers', p: 'Touch-and-go (land and take off without stopping), stop-and-go (land, come to a stop, then depart), low approach (fly the runway without touching down), and a full-stop landing. The option includes them all.' },
      { h: 'Stay predictable', p: 'Even though you can choose, do not surprise the tower. If traffic is tight they may restrict you — “option approved, full stop” — and you read back the restriction.' },
      { h: 'Drill it', p: 'Practice the option request and read-back on Clearspar so it is one less thing you are decoding in the pattern. Free, no mic.' },
    ],
  },
  {
    slug: 'contact-vs-monitor-frequency-handoff',
    title: '“Contact” vs “monitor”: frequency handoffs explained',
    description: 'The difference between “contact tower” and “monitor tower,” what to do for each, and how to handle a frequency change cleanly.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 5,
    lead: 'ATC hands you from one frequency to the next all day, and there is a small but real difference between being told to “contact” the next controller and to “monitor” them.',
    sections: [
      { h: '“Contact”', p: 'When ATC says “contact tower on one one niner point three,” you switch and check in with a call: “Tower, Cessna One Two Three Four Five, with you.” They are expecting to hear from you.' },
      { h: '“Monitor”', p: 'When ATC says “monitor tower,” you switch to the frequency and just listen. You do not check in — the tower already has your information from the hand-off and will call you. Checking in anyway only adds clutter.' },
      { h: 'Read back the frequency', p: 'Either way, read back the frequency before you switch: “Contact tower one one niner point three, One Two Three Four Five.” It confirms you dialed the right numbers.' },
      { h: 'Switch, then talk', p: 'Change the frequency first, listen for a moment so you are not stepping on another transmission, then make your call if you were told to contact.' },
      { h: '“Remain this frequency”', p: 'Sometimes ATC keeps you where you are — “remain this frequency.” Just acknowledge with your call sign; there is nothing to switch.' },
      { h: 'Why monitor exists', p: 'At a busy field, having every hand-off check in would jam the frequency. “Monitor” lets the controller sequence you in without the extra call, so do not undo it by checking in.' },
      { h: 'Drill the handoffs', p: 'Practice contact and monitor calls on Clearspar until the difference is automatic. Free, works offline, no mic.' },
    ],
  },
  {
    slug: 'progressive-taxi-lost-taxiways',
    title: 'Progressive taxi: what to say when you are lost on the taxiways',
    description: 'How to ask for progressive taxi at an unfamiliar airport — the call, what ATC gives you back, and how to read each step.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 5,
    lead: 'Getting turned around on the ground at a big unfamiliar airport is normal and nothing to be embarrassed about. There is a standard call for exactly this, and using it is the professional move.',
    sections: [
      { h: 'What progressive taxi is', p: 'Instead of a full route you have to follow on your own, ATC gives you turn-by-turn instructions one step at a time. You ask for it whenever you do not know the airport well enough to follow a route yourself.' },
      { h: 'How to ask for it', p: 'Keep it simple and honest: “Ground, Cessna One Two Three Four Five, request progressive taxi to the general aviation ramp.” You do not need a reason — controllers hear it constantly.' },
      { h: 'What you get back', p: 'One instruction at a time: “turn left on Bravo, hold short of runway two five.” You read it back, taxi it, and they give you the next step when you get there.' },
      { h: 'Read back every step', p: 'Treat each instruction like any taxi clearance — read back the route and any hold-short verbatim, including the runway number. The hold-short is the one you can never drop.' },
      { h: 'If you are already moving and lost', p: 'Stop. Hold position, then say “Ground, One Two Three Four Five, I am disoriented, request progressive taxi.” Stopping on a taxiway is always safe; guessing at a turn is not.' },
      { h: 'Why it is not embarrassing', p: 'A controller would far rather give you progressive taxi than have you wander onto a runway you were not cleared to cross. Asking is what a careful pilot does.' },
      { h: 'Drill it before you need it', p: 'Ground and taxi calls are the most-failed and the most drillable. Practice graded taxi and hold-short read-backs on Clearspar — free, no mic.' },
    ],
  },
  {
    slug: 'clearance-amendment-readback',
    title: 'When ATC changes your clearance in the air: reading back an amendment',
    description: 'Heading and altitude amendments, frequency changes, and the curveballs ATC throws after your first readback — how to catch them and read them back.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 5,
    lead: 'You read back the clearance, you settle in, and then ATC comes back with a change. The amendment is where read-backs fall apart, because habit fights the new number. Here is how to stay ahead of it.',
    sections: [
      { h: 'What an amendment is', p: 'ATC changes something already issued — a new heading, a new altitude, a frequency, or a routing. The amendment replaces the old instruction the moment you read it back.' },
      { h: 'Catch the new number', p: 'The trap is hearing the change but reading back the old value out of muscle memory. Write the new number down before you key the mic, then read what you wrote.' },
      { h: 'Heading amendment', p: '“Cessna One Two Three Four Five, turn left heading two seven zero.” Read back both the direction and the number: “Left heading two seven zero, One Two Three Four Five.”' },
      { h: 'Altitude amendment', p: '“Climb and maintain six thousand.” Read it back word for word — altitude is the one ATC will absolutely correct you on, and the one that keeps you separated from other traffic.' },
      { h: 'Frequency change', p: '“Contact approach on one two four point seven.” Read back the frequency, switch, then make your new call. Reading it back first means you never lose the number mid-switch.' },
      { h: 'When you did not catch it', p: '“Say again” is always the right answer. Never read back a guess on an amendment — a wrong read-back the controller misses is worse than asking twice.' },
      { h: 'Drill the curveballs', p: 'Clearspar has an amendment mode where ATC throws a change after your first read-back, exactly like the real thing. Practice it free until the new number comes naturally.' },
    ],
  },
  {
    slug: 'phonetic-alphabet-numbers-radio',
    title: 'Niner, tree, fife: saying letters and numbers on the radio',
    description: 'The aviation phonetic alphabet and the way pilots say numbers — niner, tree, fife, decimal — and the small mistakes that mark you as new.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 5,
    lead: 'Nothing marks a brand-new pilot faster than saying numbers like you are reading them off a page. The aviation way is small, specific, and quick to pick up.',
    sections: [
      { h: 'Why aviation changes some numbers', p: 'Radios are noisy and a few numbers sound alike, so aviation says them differently: three becomes “tree,” five becomes “fife,” and nine becomes “niner” — each tweaked so it stays distinct through static and a busy frequency.' },
      { h: 'The phonetic alphabet', p: 'Alpha, Bravo, Charlie, Delta, and on through Zulu — you use it for your call sign, taxiway names, and anything that has to be unmistakable through noise. It is worth knowing cold.' },
      { h: 'Saying your call sign', p: 'N12345 is “November One Two Three Four Five.” Once the controller shortens it to the last three, you can use the short form too — but you start with the full one.' },
      { h: 'Altitudes and headings', p: 'Said digit by digit: a heading is always three digits, “zero niner zero,” never “ninety.” Running the numbers together is the giveaway that someone is new.' },
      { h: 'Frequencies', p: '“One one niner point seven,” or “one one niner decimal seven” — both are fine. Digit by digit, then the word point or decimal, then the rest.' },
      { h: 'The common tells', p: 'Saying “ninety” for a heading, mashing numbers together, or skipping the phonetic on your call sign. Each is a tiny fix that instantly sounds more squared-away.' },
      { h: 'Drill it', p: 'Clearspar has a phonetics drill that turns letters and numbers into reflexes. Free, works offline, no mic — practice on the ramp or the couch.' },
    ],
  },
  {
    slug: 'flight-plan-vs-flight-following',
    title: 'Flight plan, flight following, or nothing: what to file and say',
    description: 'The difference between a VFR flight plan and VFR flight following, when to use each, and what you actually say on the radio.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 5,
    lead: 'New pilots mix up the VFR flight plan and flight following constantly — they are two different things that do two different jobs. Here is which to use, and the words for each.',
    sections: [
      { h: 'They are not the same thing', p: 'A VFR flight plan is a search-and-rescue safety net you file and open. Flight following is real-time traffic advisories from ATC. You can use one, both, or neither on any flight.' },
      { h: 'The VFR flight plan', p: 'You file it ahead of time, then open it with Flight Service after takeoff and close it when you land. If you forget to close it, they will start a search for you — closing it is not optional.' },
      { h: 'Flight following', p: 'You request it from approach or center in the air. They assign you a squawk code and call out nearby traffic. You cancel it when you no longer want it or are landing where they cannot follow you.' },
      { h: 'The radio call for flight following', p: '“Approach, Cessna One Two Three Four Five, request flight following.” When they answer, give your position, altitude, and destination. Read back the squawk code they assign.' },
      { h: 'When to use which', p: 'A flight plan is the safety net for remote, mountainous, or over-water legs where a search would matter. Flight following is worth requesting almost any time you want another set of eyes on traffic. Doing both is common.' },
      { h: 'The mistake to avoid', p: 'Thinking flight following replaces closing your flight plan. They are separate systems — if you filed and opened a flight plan, you still have to close it, no matter who you were talking to.' },
      { h: 'Drill the calls', p: 'Practice the flight-following request and read-back on Clearspar so the words are automatic when approach answers. Free, no mic required.' },
    ],
  },
  {
    slug: 'say-again-unable-radio-recovery',
    title: '“Say again,” “unable,” and the words that buy you time',
    description: 'The short phrases that keep you in control when you fall behind on the radio — say again, unable, standby — and how to use them without sounding lost.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 5,
    lead: 'Every pilot falls behind the radio sometimes — controllers included. The difference between a pro and a rattled student is a handful of short phrases that buy time and keep you in command.',
    sections: [
      { h: '“Say again”', p: 'When you missed it or did not understand, say “say again.” It is not an admission of weakness — it is the correct, expected call, and it is always better than reading back a guess.' },
      { h: '“Say again all after…”', p: 'When you caught part of it, ask for just the part you missed: “say again all after runway.” It is faster for both of you than repeating the whole transmission.' },
      { h: '“Unable”', p: 'When ATC asks for something you cannot safely do — a climb rate you do not have, a heading into weather — say “unable.” You are pilot in command, and they will give you an alternative.' },
      { h: '“Standby”', p: 'When you need a moment before you can respond, say “standby.” It tells the controller you heard them and will be right back, so they stop repeating the call.' },
      { h: 'Do not go silent', p: 'The worst response to falling behind is saying nothing — the controller assumes you did not hear and starts stacking up repeats. A quick “standby” keeps the frequency calm.' },
      { h: 'The real fix is slowing down', p: 'When you are behind, the answer is almost always to slow down, fly the airplane first, and use these phrases to reset the pace. They are tools, not failures.' },
      { h: 'Drill them', p: 'These phrases only help if they are reflexive. Practice the calls and read-backs on Clearspar until “say again” and “unable” come out without thinking. Free, no mic.' },
    ],
  },
  {
    slug: 'airspace-entry-radio-calls',
    title: 'Class B, C, D, E, G: what you actually have to say to enter each',
    description: 'The radio call — or lack of one — you need to enter each class of US airspace. The exact words for Class B, the two-way rule for C and D, and what E and G require.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 6,
    lead: 'Airspace looks complicated on a sectional, but the radio side comes down to one question per class: do you need a clearance, just two-way contact, or nothing at all? Here is the answer, class by class, with the words.',
    sections: [
      { h: 'The one question that matters', p: 'For VFR, every class of airspace answers the same question — what do you need before you enter? Class B needs an explicit clearance. Class C and D need two-way radio contact established. Class E and G usually need nothing on the radio. Get that framework and the phraseology follows.' },
      { h: 'Class B — you need the magic words', p: 'Class B (the big metro airports) requires an explicit clearance to enter. You call approach with your position and request, and you may not enter until you hear the specific words: “Cleared into the Class Bravo.” “Radar contact” or “standby” is not a clearance. No clearance, no entry.' },
      { h: 'Class C — two-way contact is the key', p: 'Class C does not need a clearance — it needs two-way radio communication established. The trigger is ATC using your call sign. If you call “Approach, Cessna One Two Three Four Five” and they answer “Cessna One Two Three Four Five, standby,” you are cleared to enter — they used your call sign. If they say “aircraft calling, standby,” they have not, and you stay out.' },
      { h: 'Class D — same rule as C', p: 'Class D (a tower without radar service) works the same way: establish two-way communication with the tower before entering. They say your call sign, you are in. They say “aircraft calling Tower, standby,” you hold outside the Class D until they address you directly.' },
      { h: 'Class E — usually nothing for VFR', p: 'Class E is controlled airspace, but as a VFR pilot you generally need no clearance and no radio call to fly in it. (IFR is different — that needs a clearance.) This is most of the airspace you are in on a cross-country at altitude.' },
      { h: 'Class G — uncontrolled, talk to traffic', p: 'Class G is uncontrolled — there is no ATC to call. Near a non-towered airport you self-announce on the CTAF so other traffic knows where you are. There is no clearance to get; the radio work is position reports to the other pilots.' },
      { h: 'The mistake that gets people', p: 'The classic error is treating a generic “standby” as your green light, or entering Class C or D before the controller has actually said your call sign. Listen for your call sign — that, not “aircraft calling, standby,” is your clearance to enter C and D. For B, listen for “cleared into the Class Bravo,” nothing less.' },
      { h: 'Drill the calls', p: 'Airspace entry is pure pattern once you know the rule per class. Practice graded Class B, C, and D entries on Clearspar — free, and it flags when you would have entered without the right words.' },
    ],
  },
  {
    slug: 'copy-ifr-clearance-craft',
    title: 'How to copy an IFR clearance: the CRAFT method',
    description: 'Copy any IFR clearance without falling behind — what CRAFT stands for, the shorthand for each line, and exactly how to read it back.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 6,
    lead: 'The first time you copy an IFR clearance it feels like ATC is reading you a phone number in a language you don’t speak. CRAFT is the shorthand instrument pilots use to catch all of it, in order, every time — so you’re filling in a form, not improvising.',
    sections: [
      { h: 'What CRAFT stands for', p: 'Clearances always come in the same order: Cleared to, Route, Altitude, Frequency, Transponder. Because the order never changes, you can pre-draw five rows and fill them in as the controller talks. That structure is the whole trick — you are never wondering what comes next.' },
      { h: 'C — Cleared to', p: 'Your destination airport (or, sometimes, a closer clearance limit). Write the identifier. “Cleared to the Hilo airport” becomes a single line: PHTO.' },
      { h: 'R — Route', p: 'Usually “as filed” — just write AF and move on. If ATC amends it (“…via radar vectors Victor 12…”), copy the change exactly; that is the part that bites people, so slow down and get it verbatim.' },
      { h: 'A — Altitude', p: 'Almost always two parts: an initial altitude and an “expect” — “maintain three thousand, expect six thousand one zero minutes after departure.” Write both. Pilots routinely drop the “expect” and the time.' },
      { h: 'F — Frequency', p: 'The departure frequency you will contact after takeoff. Write the numbers; you will read them back and dial them in before you roll.' },
      { h: 'T — Transponder', p: 'Your squawk code, four digits. Set it as soon as you have read it back so you do not forget.' },
      { h: 'The shorthand in practice', p: 'Before you call clearance, draw the CRAFT grid on your kneeboard. Example fill: C: PHTO · R: AF · A: 3,000 / exp 6,000 / 10 min · F: 119.7 · T: 4271. Five lines, the whole clearance.' },
      { h: 'Reading it back', p: 'Read it back in the same order you copied it. The controller is listening for the altitude, frequency, and squawk especially — those are the ones they will correct you on. Same order every time means you never lose your place.' },
      { h: 'Drill it until it is automatic', p: 'Clearance copy is pure pattern recognition, and it is 100% drillable on the ground. Practice graded IFR clearances on Clearspar — free, and it flags exactly which line you dropped.' },
    ],
  },
  {
    slug: 'mayday-vs-pan-pan',
    title: 'Mayday vs Pan-Pan: emergency radio calls, exactly what to say',
    description: 'When to declare Mayday vs Pan-Pan, the exact call format, and what to say so ATC can help you fast.',
    date: '2026-06-28',
    author: 'Clearspar',
    readMins: 6,
    lead: 'Most pilots never make an emergency call — which is exactly why it is worth rehearsing the words now, calmly, so they are there when you need them. Mayday versus Pan-Pan, and the format for each, is simpler than it sounds.',
    sections: [
      { h: 'Mayday vs Pan-Pan', p: 'Mayday is distress: grave and imminent danger, you need help now. Pan-Pan (said “pan pan”) is urgency: you have a serious problem but it is not yet life-threatening. You say the word three times — “Mayday, Mayday, Mayday” — so there is no mistaking it through a noisy frequency.' },
      { h: 'When it is a Mayday', p: 'Engine failure, fire, smoke, structural problem, a medical emergency that threatens life, loss of control — anything where the outcome is in doubt. Do not talk yourself out of it; declaring gets you priority handling and every resource ATC has.' },
      { h: 'When it is a Pan-Pan', p: 'Unsure of your position, a rough-running engine that is still producing power, low fuel that is not critical yet, a sick passenger who is stable, a partial equipment failure. It tells ATC you may need help soon without triggering a full emergency response.' },
      { h: 'The call format', p: 'After the Mayday or Pan-Pan, give ATC what they need: who you are calling, who you are (call sign and type), where you are and your altitude, the nature of the problem, and your intentions. If there is time, add souls on board and fuel remaining.' },
      { h: 'A Mayday example', p: '“Mayday, Mayday, Mayday, Honolulu Approach, Cessna One Two Three Four Five, engine failure, eight miles south of the field at three thousand, gliding toward the airport, three souls on board, two hours fuel.”' },
      { h: 'A Pan-Pan example', p: '“Pan-Pan, Pan-Pan, Pan-Pan, Honolulu Approach, Cessna One Two Three Four Five, I am unsure of my position, last known fifteen miles west of the field at four thousand five hundred, request assistance.”' },
      { h: 'After the call', p: 'Aviate, navigate, communicate — in that order. Fly the airplane first. Squawk 7700 if you are not already on a discrete code; it lights you up on every controller’s scope. Then do what the controller asks, but remember you are pilot in command — you can deviate from any rule to handle the emergency.' },
      { h: 'Rehearse it before you need it', p: 'The words should be muscle memory, not something you invent under stress. Practice emergency calls calmly on Clearspar so they are automatic.' },
    ],
  },
  {
    slug: 'ground-tower-departure-every-call',
    title: 'What to say to Ground, Tower, and Departure — every call, in order',
    description: 'The complete towered-airport departure sequence — clearance delivery, ground, tower, and the departure handoff — with the exact words and readbacks for each frequency.',
    date: '2026-06-24',
    author: 'Clearspar',
    readMins: 7,
    lead: 'A departure from a towered airport is a relay race across three or four frequencies, and each one has a specific call. Once you know the order and the script for each handoff, the whole chain stops feeling like improvisation. Here is every call, start to wheels-up and beyond.',
    sections: [
      { h: '1. ATIS — copy it before you key up', p: 'Tune the ATIS first and write down the active runway, altimeter, and the information letter. You will quote it on your first call — "with information Charlie" — so the controller knows you already have the weather and does not have to read it to you. Skipping this is the fastest way to fall behind before you have said a word.' },
      { h: '2. Clearance Delivery — when the field has one', p: 'At busier Class C and B fields, get your clearance before you taxi. VFR it is short: "Clearance Delivery, Cessna One Two Three Four Five, VFR to the north, request departure." You will usually get a squawk code and sometimes a heading or altitude — read all of it back. IFR, tell them "ready to copy" and read back the full clearance: cleared-to, route, altitude, frequency, transponder. Smaller Class D fields skip this and you go straight to Ground.' },
      { h: '3. Ground — taxi to the runway', p: 'From the ramp: "Ground, Cessna One Two Three Four Five, at the south ramp, taxi for departure, with information Charlie." Read back the full taxi route and — verbatim, including the runway number — any hold-short instruction: "Taxi to runway two five via Alpha, hold short of runway one niner, Cessna One Two Three Four Five." The hold-short is the one item you never paraphrase.' },
      { h: '4. Tower — takeoff clearance', p: 'At the hold-short line, switch to Tower: "Tower, Cessna One Two Three Four Five, holding short runway two five, ready for departure." When the clearance comes, read it back with the runway: "Cleared for takeoff runway two five, Cessna One Two Three Four Five." If you are told to "line up and wait," read that back too — it is not a clearance to depart.' },
      { h: '5. Departure — the handoff after takeoff', p: 'Once airborne, Tower hands you off: "Contact Departure." Switch to the new frequency and check in with who you are and your altitude: "SoCal Departure, Cessna One Two Three Four Five, two thousand, climbing four thousand five hundred." Read back any heading or altitude they assign. If you asked for flight following, this is where the traffic advisories start.' },
      { h: 'The thread that ties it together', p: 'Every readback ends with your call sign, and anything that changes where the airplane goes — runway, hold-short, heading, altitude, frequency, squawk — gets said back in full. "Roger" is not a readback. If a transmission comes fast, "say again" is always the professional move. Run the chain a few times on the ground and it becomes a script you follow, not a test you fail.' },
    ],
  },
  {
    slug: 'stop-freezing-on-the-radio',
    title: 'Why student pilots freeze on the radio — and how to fix it',
    description: 'Blanking when ATC calls is the most common fear in primary training. Here is why your brain locks up, and the specific habits and drills that make radio calls automatic.',
    date: '2026-06-24',
    author: 'Clearspar',
    readMins: 6,
    lead: 'Almost every student pilot hits the same wall: ATC keys up, your mind goes blank, you read back something garbled, then spend the next two minutes replaying it instead of flying the airplane. It is not a talent problem — it is a working-memory problem, and it is fixable.',
    sections: [
      { h: 'Why your brain blanks', p: 'Early in training, flying the airplane already uses almost all of your attention. When a fast clearance arrives there is no spare working memory left to hold it, so it evaporates the instant the controller stops talking. This is task saturation, and it happens to every new pilot. The fix is not "try harder in the moment" — it is to make the radio cost less attention so there is room for it.' },
      { h: 'Pre-load the call before you key up', p: 'Most of the freeze comes from improvising. Instead, think the expected call before you transmit. Before calling ground, line up the things you will read back: taxi route, hold short, altimeter. Now you are confirming a script you already have rather than composing one under pressure. Pilots who pre-load almost never blank.' },
      { h: 'Learn the script — most calls are templates', p: 'ATC communication is far more scripted than it sounds. A ground call, a position report, a flight-following request each follows a fixed pattern: who you are calling, who you are, where and what, your request. Once the templates are memorized, a real transmission is just filling in the blanks — a fraction of the attention.' },
      { h: 'Drill readbacks until they are automatic', p: 'The call blanks because it is not yet automatic, and you cannot make it automatic by only practicing in the airplane, where reps are rare and expensive. The fix is reps on the ground: hear a clearance, read it back, see exactly which required elements you dropped, and repeat until the words come without thought. Ten minutes a day of graded readbacks beats a dozen flights of hoping it clicks.' },
      { h: 'In the moment: slow down and ask', p: 'When you do fall behind, the professional move is to ask. "Say again" — or "say again slower" — is normal; airline crews use it every day. Write the clearance down as you copy it. A two-second pause to get it right beats a confident readback of the wrong runway, and controllers would far rather repeat than untangle a mistake.' },
    ],
  },
  {
    slug: 'first-call-towered-airport',
    title: 'How to talk to ATC at a towered field for the first time',
    description: 'The exact calls — ground, tower, and the readbacks — for your first flight into a towered airport, with examples you can copy.',
    date: '2026-06-18',
    author: 'Clearspar',
    readMins: 6,
    lead: 'The radio is the part most student pilots dread, but a towered field follows a script. Learn the script and the nerves go away. Here is the whole sequence, in order, with example calls.',
    sections: [
      { h: 'Listen to ATIS first', p: 'Before you say a word, tune the ATIS and copy the weather, active runway, and the information letter. On your first call you tell the controller you have it: "with information Bravo." That tells them not to read it all to you.' },
      { h: 'Call Ground to taxi', p: 'From the ramp, call Ground: "Palmdale Ground, Cessna One Two Three Four Five, at the south ramp, taxi for departure, with information Bravo." Read back the taxi route and — verbatim — any hold-short: "Taxi to runway two five via Alpha, hold short of runway one niner, Cessna One Two Three Four Five."' },
      { h: 'Switch to Tower for takeoff', p: 'At the hold-short line, switch to Tower: "Palmdale Tower, Cessna One Two Three Four Five, holding short runway two five, ready for departure." When cleared, read it back with the runway: "Cleared for takeoff runway two five, Cessna One Two Three Four Five."' },
      { h: 'The golden rule of readbacks', p: 'Read back anything that affects where you go: runway assignments, hold-shorts, altitudes, headings, frequencies, and squawk codes. "Roger" is not a readback — say the words back.' },
      { h: 'When you fall behind', p: 'If a controller talks faster than you can copy, say "say again" and write it down. Everyone — including airline crews — asks for a repeat. It is far better than guessing.' },
    ],
  },
  {
    slug: 'readbacks-that-fail-checkrides',
    title: 'The readbacks that fail checkrides — and how to nail them',
    description: 'The handful of radio mistakes examiners watch for, and the exact phraseology that keeps you on the right side of them.',
    date: '2026-06-16',
    author: 'Clearspar',
    readMins: 5,
    lead: 'Examiners are not grading your radio voice — they are grading whether you read back the safety-critical items correctly. Miss one of these and it shows up in the debrief.',
    sections: [
      { h: 'Dropping the runway from a hold-short', p: 'Per AIM 4-3-18, a hold-short must be read back including the runway number. "Hold short of runway two six" → "Hold short of runway two six, Cessna One Two Three Four Five." Reading back the taxi route but skipping the hold-short is the classic miss.' },
      { h: 'Saying "roger" to a clearance', p: 'A landing or takeoff clearance, an altitude, a heading — all must be read back. "Roger" only means you received the transmission. If it changes where the airplane goes, say it back.' },
      { h: 'Garbling numbers', p: 'Read numbers digit by digit and use niner, fife, tree. "One two zero point niner" — not "one twenty point nine." Altitudes use thousands and hundreds: "four thousand five hundred."' },
      { h: 'Forgetting your call sign', p: 'Every readback ends with who you are. It closes the loop so the controller knows the right aircraft copied.' },
      { h: 'Not asking when unsure', p: 'If you do not understand an instruction, "say again" or "unable" are correct, professional answers. Acting on a clearance you did not understand is the real failure.' },
    ],
  },
  {
    slug: 'non-towered-radio-calls',
    title: 'Non-towered airport radio calls, explained',
    description: 'There is no controller at a non-towered field — you announce your own position on the CTAF. The standard self-announce calls, in order.',
    date: '2026-06-13',
    author: 'Clearspar',
    readMins: 5,
    lead: 'At a non-towered airport nobody clears you to do anything — you see, avoid, and announce. The calls follow a simple pattern, and bracketing them with the field name is what keeps everyone on the same page.',
    sections: [
      { h: 'The self-announce format', p: 'Airport name, who you are, where and what, airport name again (AIM 4-1-9): "Lincoln traffic, Skyhawk Four Five X-ray, left downwind runway one eight, Lincoln." Bracketing with the field name lets pilots scanning frequencies know which airport you mean.' },
      { h: 'Inbound', p: 'About ten miles out: "Lincoln traffic, Cessna One Two Three Four Five, one zero miles south, inbound landing, Lincoln." Then announce your pattern entry.' },
      { h: 'In the pattern', p: 'Announce each leg with intentions: entering downwind, turning base, turning final, and clear of the runway. Say what you are doing, not just where you are.' },
      { h: 'Departing', p: 'Before you taxi onto the runway: "Lincoln traffic, Cessna One Two Three Four Five, departing runway one eight, departing to the south, Lincoln."' },
      { h: 'No radio? Still legal — still see and avoid', p: 'Radios are recommended, not required, at most non-towered fields. Keep your eyes outside; the announcements supplement looking, they do not replace it.' },
    ],
  },
  {
    slug: 'request-flight-following',
    title: 'How to request VFR flight following (and why you should)',
    description: 'Flight following gives you traffic advisories and a controller watching your route. Exactly how to ask, what to read back, and how to end it.',
    date: '2026-06-10',
    author: 'Clearspar',
    readMins: 4,
    lead: 'Flight following is free, makes you a better-protected VFR pilot, and is great radio practice. Many students never ask for it simply because they are not sure how. Here is the whole exchange.',
    sections: [
      { h: 'Who to call', p: 'Call the Approach or Center facility for your area. Give type, position, altitude, and the request: "Norcal Approach, Cessna One Two Three Four Five, ten miles south of Livermore, four thousand five hundred, request VFR flight following to Salinas."' },
      { h: 'Set the squawk', p: 'ATC assigns a discrete code: "squawk zero two three four." Read it back, set it, and wait for "radar contact."' },
      { h: 'Working the traffic calls', p: 'You will get advisories by clock position, distance, and altitude. Reply "traffic in sight" or "looking, negative contact." You are still responsible for see-and-avoid — flight following helps, it does not replace your eyes.' },
      { h: 'Ending the service', p: 'ATC may say "radar service terminated, squawk VFR, frequency change approved," or you can cancel any time: "Cessna One Two Three Four Five, cancel flight following." Set 1200 and carry on.' },
    ],
  },
]

export function getPost(slug: string): BlogPost | undefined {
  return POSTS.find((p) => p.slug === slug)
}
