// Private Pilot knowledge-test prep. Original questions written to the FAA PA-ACS
// knowledge areas (the FAA's public question bank was retired) — accurate, with
// explanations. Multiple choice; `answer` is the index into `choices`.
export interface WrittenQ {
  id: string
  category: string
  q: string
  choices: string[]
  answer: number
  explain: string
}

export const WRITTEN: WrittenQ[] = [
  // Regulations
  { id: 'w1', category: 'Regulations', q: 'For a day VFR flight, what is the minimum fuel reserve?', choices: ['Enough to fly to the destination', 'Enough to fly to the first point of intended landing plus 30 minutes at normal cruise', 'Enough to fly to the first point of intended landing plus 45 minutes', '1 hour at cruise'], answer: 1, explain: 'FAR 91.151: day VFR requires fuel to reach the first point of intended landing plus 30 minutes at normal cruise; night VFR is 45 minutes.' },
  { id: 'w2', category: 'Regulations', q: 'Which documents must be aboard the aircraft (ARROW)?', choices: ['Airworthiness, Registration, Radio license, Operating limitations, Weight & balance', 'Airworthiness, Registration, pilot certificate, logbook, charts', 'Registration, medical, insurance, POH, charts', 'Airworthiness, medical, registration, ELT card, charts'], answer: 0, explain: 'ARROW: Airworthiness cert, Registration, Radio station license (international only), Operating limitations (POH/placards), Weight & balance data.' },
  { id: 'w3', category: 'Regulations', q: 'To carry passengers, you must have made how many takeoffs and landings recently?', choices: ['3 in the preceding 90 days, same category and class', '3 in the preceding 12 months', '1 in the preceding 30 days', '3 in the preceding 6 calendar months'], answer: 0, explain: 'FAR 61.57: 3 takeoffs and landings within the preceding 90 days in the same category, class, and type (if type-rated). Night/tailwheel have added requirements.' },
  { id: 'w4', category: 'Regulations', q: 'Preflight action required for every flight (FAR 91.103) includes:', choices: ['Only checking the weather', 'Weather, fuel requirements, alternatives, runway lengths, and takeoff/landing distances', 'Filing a flight plan', 'A maintenance logbook review'], answer: 1, explain: 'FAR 91.103 requires all available information: weather, fuel, alternatives if the flight cannot be completed, known traffic delays, runway lengths, and takeoff/landing performance.' },

  // Airspace
  { id: 'w5', category: 'Airspace', q: 'What is required to enter Class B airspace?', choices: ['Two-way radio contact', 'A clearance — the controller must say "cleared into the Class Bravo"', 'A Mode C transponder only', 'A flight plan'], answer: 1, explain: 'Class B requires a specific clearance to enter (plus Mode C and, at the primary airport, at least a private certificate or student endorsement).' },
  { id: 'w6', category: 'Airspace', q: 'VFR weather minimums in Class E below 10,000 ft MSL are:', choices: ['1 SM and clear of clouds', '3 SM, 500 below / 1,000 above / 2,000 horizontal from clouds', '5 SM, 1,000 below / 1,000 above / 1 mile horizontal', '3 SM and clear of clouds'], answer: 1, explain: 'Below 10,000 MSL in controlled airspace: 3 SM visibility and 500 ft below, 1,000 ft above, 2,000 ft horizontal from clouds.' },
  { id: 'w7', category: 'Airspace', q: 'What equipment is required to operate in Class C airspace?', choices: ['Two-way radio and a Mode C transponder', 'A clearance to enter', 'Mode C transponder only', 'ADS-B and a flight plan'], answer: 0, explain: 'Class C requires two-way radio communication established and a Mode C (altitude-encoding) transponder. No explicit "cleared to enter" is needed — two-way contact is the gate.' },
  { id: 'w8', category: 'Airspace', q: 'In Class G airspace, daytime at or below 1,200 ft AGL, VFR minimums are:', choices: ['3 SM and clear of clouds', '1 SM and clear of clouds', '1 SM, 500 below / 1,000 above / 2,000 horizontal', '5 SM and 1,000 ft below clouds'], answer: 1, explain: 'Class G, day, ≤1,200 AGL: 1 SM and clear of clouds. (Night requires 3 SM and the standard cloud clearances.)' },

  // Weather
  { id: 'w9', category: 'Weather', q: 'Standard temperature and pressure at sea level are:', choices: ['15°C and 29.92 in Hg', '0°C and 30.00 in Hg', '20°C and 29.92 in Hg', '15°F and 29.92 in Hg'], answer: 0, explain: 'ISA standard sea-level conditions: 15°C and 29.92 inches of mercury, with a standard lapse rate of about 2°C per 1,000 ft.' },
  { id: 'w10', category: 'Weather', q: 'Fog is most likely to form when:', choices: ['The temperature/dewpoint spread is large', 'The temperature and dewpoint are close together', 'Winds are strong', 'The air is very dry'], answer: 1, explain: 'Fog forms as the temperature cools toward the dewpoint (a small temperature/dewpoint spread). A narrowing spread is a fog warning sign.' },
  { id: 'w11', category: 'Weather', q: 'Stable air is typically associated with:', choices: ['Cumuliform clouds and good visibility', 'Stratiform clouds, steady precipitation, and poor visibility', 'Turbulence and showers', 'Thunderstorms'], answer: 1, explain: 'Stable air resists vertical motion: stratiform (layered) clouds, steady precip, smooth air, and often poor visibility/haze. Unstable air gives cumuliform clouds, showers, and turbulence.' },
  { id: 'w12', category: 'Weather', q: 'The ultimate source of all weather is:', choices: ['The jet stream', 'Uneven heating of the Earth by the sun', 'Ocean currents', 'The Coriolis effect'], answer: 1, explain: 'Uneven solar heating of the Earth’s surface drives the temperature and pressure differences that create all weather.' },

  // Aerodynamics
  { id: 'w13', category: 'Aerodynamics', q: 'An airplane stalls when:', choices: ['Airspeed drops below a fixed number', 'The critical angle of attack is exceeded', 'The engine quits', 'It is in a steep bank only'], answer: 1, explain: 'A wing stalls when it exceeds its critical angle of attack — which can happen at ANY airspeed or attitude, not just slow flight.' },
  { id: 'w14', category: 'Aerodynamics', q: 'In a level 60° banked turn, the load factor is approximately:', choices: ['1 G', '1.5 Gs', '2 Gs', '4 Gs'], answer: 2, explain: 'A level 60° bank pulls about 2 Gs, which also raises stall speed by roughly 40%.' },
  { id: 'w15', category: 'Aerodynamics', q: 'Left-turning tendency on takeoff is caused by:', choices: ['Crosswind only', 'Torque, P-factor, spiraling slipstream, and gyroscopic precession', 'Weight and balance', 'The ailerons'], answer: 1, explain: 'The four left-turning tendencies: engine torque, P-factor (asymmetric propeller load), spiraling slipstream, and gyroscopic precession.' },
  { id: 'w16', category: 'Aerodynamics', q: 'Ground effect occurs:', choices: ['At any altitude', 'Within about one wingspan of the surface, reducing induced drag', 'Only on the ground', 'During cruise'], answer: 1, explain: 'Within roughly one wingspan of the surface the wingtip vortices are reduced, cutting induced drag — the airplane can feel like it wants to float.' },

  // Performance & W&B
  { id: 'w17', category: 'Performance', q: 'A higher density altitude results in:', choices: ['Improved performance', 'Decreased engine, propeller, and wing performance', 'No change', 'Better climb only'], answer: 1, explain: 'High density altitude (thin air) reduces power, propeller thrust, and lift — longer takeoff rolls and weaker climb.' },
  { id: 'w18', category: 'Performance', q: 'Density altitude increases with:', choices: ['Low temperature and low elevation', 'High temperature, high elevation, and high humidity', 'High pressure', 'Cold, dry air'], answer: 1, explain: 'Hot, high, and humid all raise density altitude (less dense air). "High, hot, and humid" is the hazard combination.' },
  { id: 'w19', category: 'Performance', q: 'A forward center of gravity:', choices: ['Lowers stall speed', 'Increases stability and stall speed and requires more elevator force', 'Makes the airplane less stable', 'Has no effect'], answer: 1, explain: 'A forward CG increases longitudinal stability and stall speed and requires more elevator/back-pressure (e.g., on landing flare).' },

  // Navigation
  { id: 'w20', category: 'Navigation', q: 'Magnetic variation is:', choices: ['The error caused by aircraft metal', 'The angle between true north and magnetic north', 'The difference between IAS and TAS', 'Caused by the wind'], answer: 1, explain: 'Variation is the angular difference between true and magnetic north; it is corrected to convert true course to magnetic course. (Deviation is the aircraft-induced compass error.)' },
  { id: 'w21', category: 'Navigation', q: 'VOR radials are oriented:', choices: ['TO the station', 'FROM the station', 'Toward magnetic north', 'Along the runway'], answer: 1, explain: 'A radial is a magnetic bearing FROM the VOR. Flying inbound on the 360 radial means tracking a 180 course to the station.' },
  { id: 'w22', category: 'Navigation', q: 'On a sectional chart, an airport depicted in blue indicates:', choices: ['A private airport', 'An airport with an operating control tower', 'A seaplane base', 'A closed airport'], answer: 1, explain: 'Blue airport symbols/text indicate a towered airport; magenta indicates non-towered.' },

  // Aeromedical
  { id: 'w23', category: 'Aeromedical', q: 'Above what cabin altitude must the required minimum flight crew use supplemental oxygen after 30 minutes?', choices: ['10,000 ft MSL', '12,500 ft MSL', '14,000 ft MSL', '15,000 ft MSL'], answer: 1, explain: 'FAR 91.211: above 12,500 ft MSL cabin altitude for more than 30 minutes, the required flight crew must use oxygen; above 14,000 it is required at all times.' },
  { id: 'w24', category: 'Aeromedical', q: 'The best response to spatial disorientation is to:', choices: ['Trust your inner ear', 'Trust and rely on the flight instruments', 'Make rapid control inputs', 'Close your eyes briefly'], answer: 1, explain: 'In reduced visual references your senses lie — rely on the instruments. This is why VFR-into-IMC is so deadly.' },
  { id: 'w25', category: 'Aeromedical', q: 'Hyperventilation is best corrected by:', choices: ['Breathing faster', 'Slowing the breathing rate, breathing into a bag, or talking aloud', 'Climbing higher', 'Using oxygen immediately'], answer: 1, explain: 'Hyperventilation (too much CO2 blown off) is relieved by slowing the breathing rate; talking aloud naturally slows it. Symptoms overlap with hypoxia, so consider both.' },
  { id: 'w26', category: 'Aeromedical', q: 'Carbon monoxide poisoning in flight most often comes from:', choices: ['The fuel tanks', 'A cracked exhaust/heater system', 'The avionics', 'High altitude'], answer: 1, explain: 'CO from engine exhaust can leak through the cabin heater. Headache, dizziness, and drowsiness are warning signs — shut the heater, open vents, and use oxygen if available.' },

  // Procedures & comms
  { id: 'w27', category: 'Procedures', q: 'The transponder code for lost communications is:', choices: ['7500', '7600', '7700', '1200'], answer: 1, explain: '7600 = lost comms, 7700 = emergency, 7500 = hijack, 1200 = VFR.' },
  { id: 'w28', category: 'Procedures', q: 'A steady green light gun signal to an aircraft in flight means:', choices: ['Return for landing', 'Cleared to land', 'Give way to other aircraft', 'Airport unsafe — do not land'], answer: 1, explain: 'In flight: steady green = cleared to land; flashing green = return for landing; steady red = give way and continue circling; flashing red = airport unsafe.' },
  { id: 'w29', category: 'Procedures', q: 'When two aircraft are converging at the same altitude (neither overtaking), right of way goes to:', choices: ['The faster aircraft', 'The aircraft to the other’s right', 'The larger aircraft', 'The one that called first'], answer: 1, explain: 'FAR 91.113: when converging, the aircraft on the right has the right of way. An aircraft in distress always has priority over all others.' },
  { id: 'w30', category: 'Procedures', q: 'At a non-towered airport you should:', choices: ['Wait for a clearance to land', 'Self-announce position and intentions on the CTAF and see-and-avoid', 'Contact the nearest tower', 'Squawk 7600'], answer: 1, explain: 'No ATC is present; announce your position/intentions on the CTAF and remain responsible for see-and-avoid.' },
]

export const WRITTEN_CATEGORIES = Array.from(new Set(WRITTEN.map((w) => w.category)))
