import Foundation

// Mirrors the Scenario shape in src/lib/types.ts. The bundled scenarios.json
// (generated by scripts/export-scenarios.mjs) is already camelCase, so this
// decodes with a plain decoder — NOT the API client's snake_case strategy.
// realField (real-geometry field) is still omitted — 0 scenarios use it.
struct Scenario: Codable, Identifiable, Hashable {
    let id: String
    let title: String
    let phase: Phase
    let difficulty: Int
    let airport: String
    let facility: Facility?
    let frequency: String?
    let setup: String
    let atcTransmission: String
    let requiredElements: [String]
    let correctReadback: String
    let commonMistakes: [String]
    let tier: String?          // "pro" for the advanced (Solo Pilot) library
    let category: String?      // "helicopter" grouping
    let pack: String?          // "hawaii" | "alaska" regional-flavor tag
    let curveball: Curveball?
    let diagram: Diagram?      // optional FAA airport-diagram chart (4 scenarios)

    var isPro: Bool { tier == "pro" }
    var isHelicopter: Bool { category == "helicopter" }

    struct Curveball: Codable, Hashable {
        let setup: String?
        let atcTransmission: String
        let requiredElements: [String]
        let correctReadback: String
    }

    // Mirrors AirportDiagram in src/lib/types.ts. The 4 scenarios that have one
    // all use a real FAA chart image (`chart`) + an ownship position; the drawn
    // schematic path (taxiways-only, no chart) isn't used by any scenario yet.
    struct Diagram: Codable, Hashable {
        let airport: String
        let chart: String?          // e.g. "/charts/phto.png" → bundled "phto.png"
        let aircraft: Ownship?
        let kind: String?
        let taxiways: [String]?
        let destRunway: String?
        let holdShortRunway: String?
        let crossRunway: String?

        struct Ownship: Codable, Hashable {
            let x: Double     // % of chart width
            let y: Double     // % of chart height
            let heading: Double
        }

        /// Bundled image name for `chart` (strips the "/charts/" path + extension).
        var chartImageName: String? {
            guard let chart else { return nil }
            return (chart as NSString).lastPathComponent
                .replacingOccurrences(of: ".png", with: "")
        }
    }

    enum Phase: String, Codable, CaseIterable {
        case ground, departure, pattern, enroute, ifr, emergency

        var label: String {
            switch self {
            case .ground: return "Ground"
            case .departure: return "Departure"
            case .pattern: return "Pattern"
            case .enroute: return "En route"
            case .ifr: return "IFR"
            case .emergency: return "Emergencies & advanced"
            }
        }
    }

    enum Facility: String, Codable, CaseIterable {
        case ground = "GROUND", tower = "TOWER", approach = "APPROACH"
        case departure = "DEPARTURE", center = "CENTER", clearance = "CLEARANCE"
        case unicom = "UNICOM", ctaf = "CTAF"
    }
}

struct DifficultyMeta {
    let label: String
    static func from(_ level: Int) -> DifficultyMeta {
        switch level {
        case 1: return DifficultyMeta(label: "Student")
        case 2: return DifficultyMeta(label: "Intermediate")
        default: return DifficultyMeta(label: "Advanced")
        }
    }
}
